"""updated question master field name

Revision ID: 1a9019e5ef9f
Revises: 44077e44448c
Create Date: 2025-07-23 14:40:13.338258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1a9019e5ef9f'
down_revision: Union[str, Sequence[str], None] = '44077e44448c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('questions', 'text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('questions', 'name')
    # ### end Alembic commands ###
