"""Updated the models relational and reverse relational fields

Revision ID: 44077e44448c
Revises: 0b02fd49f992
Create Date: 2025-07-21 16:29:00.515864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '44077e44448c'
down_revision: Union[str, Sequence[str], None] = '0b02fd49f992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('category', 'first_name')
    op.drop_constraint(op.f('thread_country_id_fkey'), 'thread', type_='foreignkey')
    op.drop_constraint(op.f('thread_subcategory_id_fkey'), 'thread', type_='foreignkey')
    op.create_foreign_key(None, 'thread', 'country', ['country_id'], ['id'])
    op.create_foreign_key(None, 'thread', 'subcategory', ['subcategory_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'thread', type_='foreignkey')
    op.drop_constraint(None, 'thread', type_='foreignkey')
    op.create_foreign_key(op.f('thread_subcategory_id_fkey'), 'thread', 'thread', ['subcategory_id'], ['id'])
    op.create_foreign_key(op.f('thread_country_id_fkey'), 'thread', 'thread', ['country_id'], ['id'])
    op.add_column('category', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('category', 'name')
    # ### end Alembic commands ###
