"""Update models for ORM-level cascading deletes

Revision ID: 55c1a9e0de40
Revises: 957001d620db
Create Date: 2025-08-27 17:07:28.600413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55c1a9e0de40'
down_revision: Union[str, Sequence[str], None] = '957001d620db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('feedback_message_id_fkey'), 'feedback', type_='foreignkey')
    op.create_foreign_key(None, 'feedback', 'message', ['message_id'], ['id'], ondelete='CASCADE')
    op.alter_column('message', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_constraint(op.f('message_thread_id_fkey'), 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'thread', ['thread_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key(op.f('message_thread_id_fkey'), 'message', 'thread', ['thread_id'], ['id'])
    op.alter_column('message', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.create_foreign_key(op.f('feedback_message_id_fkey'), 'feedback', 'message', ['message_id'], ['id'])
    # ### end Alembic commands ###
