"""Create model for scraped url

Revision ID: 957001d620db
Revises: d1ec7b2f83ab
Create Date: 2025-08-20 17:53:35.357317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '957001d620db'
down_revision: Union[str, Sequence[str], None] = 'd1ec7b2f83ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraped_page',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country_id', sa.Uuid(), nullable=False),
    sa.Column('last_scraped_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraped_page_url'), 'scraped_page', ['url'], unique=True)
    op.drop_constraint(op.f('uq_feedback_message_id'), 'feedback', type_='unique')
    op.drop_constraint(op.f('feedback_message_id_fkey'), 'feedback', type_='foreignkey')
    op.create_foreign_key(None, 'feedback', 'message', ['message_id'], ['id'])
    op.drop_constraint(op.f('message_thread_id_fkey'), 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'thread', ['thread_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key(op.f('message_thread_id_fkey'), 'message', 'thread', ['thread_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.create_foreign_key(op.f('feedback_message_id_fkey'), 'feedback', 'message', ['message_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_feedback_message_id'), 'feedback', ['message_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_scraped_page_url'), table_name='scraped_page')
    op.drop_table('scraped_page')
    # ### end Alembic commands ###
