from .prompt_constant import PromptConstant
from .questions_data import QUESTIONS_DATA
from .legislation_unused_url import legislation_unused_urls
from .question_wise_text import QUESTION_WISE_TEXT, QUESTION_WISE_RULES